/*
 * Wallet
 * User application
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.wallet.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * AuthClientDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-24T22:57:23.435-05:00")
public class AuthClientDetail implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("_id")
  private String id = null;

  @SerializedName("accessTokenValidity")
  private Integer accessTokenValidity = null;

  @SerializedName("additionalInformation")
  private String additionalInformation = null;

  @SerializedName("authorities")
  private String authorities = null;

  @SerializedName("autoapprove")
  private String autoapprove = null;

  @SerializedName("clientId")
  private String clientId = null;

  @SerializedName("clientSecret")
  private String clientSecret = null;

  @SerializedName("grantTypes")
  private String grantTypes = null;

  @SerializedName("partnerId")
  private String partnerId = null;

  @SerializedName("redirectUri")
  private String redirectUri = null;

  @SerializedName("refreshTokenValidity")
  private Integer refreshTokenValidity = null;

  @SerializedName("resourcesIds")
  private String resourcesIds = null;

  @SerializedName("scope")
  private String scope = null;

  public AuthClientDetail id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AuthClientDetail accessTokenValidity(Integer accessTokenValidity) {
    this.accessTokenValidity = accessTokenValidity;
    return this;
  }

   /**
   * Get accessTokenValidity
   * @return accessTokenValidity
  **/
  @ApiModelProperty(value = "")
  public Integer getAccessTokenValidity() {
    return accessTokenValidity;
  }

  public void setAccessTokenValidity(Integer accessTokenValidity) {
    this.accessTokenValidity = accessTokenValidity;
  }

  public AuthClientDetail additionalInformation(String additionalInformation) {
    this.additionalInformation = additionalInformation;
    return this;
  }

   /**
   * Get additionalInformation
   * @return additionalInformation
  **/
  @ApiModelProperty(value = "")
  public String getAdditionalInformation() {
    return additionalInformation;
  }

  public void setAdditionalInformation(String additionalInformation) {
    this.additionalInformation = additionalInformation;
  }

  public AuthClientDetail authorities(String authorities) {
    this.authorities = authorities;
    return this;
  }

   /**
   * Get authorities
   * @return authorities
  **/
  @ApiModelProperty(value = "")
  public String getAuthorities() {
    return authorities;
  }

  public void setAuthorities(String authorities) {
    this.authorities = authorities;
  }

  public AuthClientDetail autoapprove(String autoapprove) {
    this.autoapprove = autoapprove;
    return this;
  }

   /**
   * Get autoapprove
   * @return autoapprove
  **/
  @ApiModelProperty(value = "")
  public String getAutoapprove() {
    return autoapprove;
  }

  public void setAutoapprove(String autoapprove) {
    this.autoapprove = autoapprove;
  }

  public AuthClientDetail clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @ApiModelProperty(value = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public AuthClientDetail clientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
    return this;
  }

   /**
   * Get clientSecret
   * @return clientSecret
  **/
  @ApiModelProperty(value = "")
  public String getClientSecret() {
    return clientSecret;
  }

  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }

  public AuthClientDetail grantTypes(String grantTypes) {
    this.grantTypes = grantTypes;
    return this;
  }

   /**
   * Get grantTypes
   * @return grantTypes
  **/
  @ApiModelProperty(value = "")
  public String getGrantTypes() {
    return grantTypes;
  }

  public void setGrantTypes(String grantTypes) {
    this.grantTypes = grantTypes;
  }

  public AuthClientDetail partnerId(String partnerId) {
    this.partnerId = partnerId;
    return this;
  }

   /**
   * Get partnerId
   * @return partnerId
  **/
  @ApiModelProperty(value = "")
  public String getPartnerId() {
    return partnerId;
  }

  public void setPartnerId(String partnerId) {
    this.partnerId = partnerId;
  }

  public AuthClientDetail redirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
    return this;
  }

   /**
   * Get redirectUri
   * @return redirectUri
  **/
  @ApiModelProperty(value = "")
  public String getRedirectUri() {
    return redirectUri;
  }

  public void setRedirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
  }

  public AuthClientDetail refreshTokenValidity(Integer refreshTokenValidity) {
    this.refreshTokenValidity = refreshTokenValidity;
    return this;
  }

   /**
   * Get refreshTokenValidity
   * @return refreshTokenValidity
  **/
  @ApiModelProperty(value = "")
  public Integer getRefreshTokenValidity() {
    return refreshTokenValidity;
  }

  public void setRefreshTokenValidity(Integer refreshTokenValidity) {
    this.refreshTokenValidity = refreshTokenValidity;
  }

  public AuthClientDetail resourcesIds(String resourcesIds) {
    this.resourcesIds = resourcesIds;
    return this;
  }

   /**
   * Get resourcesIds
   * @return resourcesIds
  **/
  @ApiModelProperty(value = "")
  public String getResourcesIds() {
    return resourcesIds;
  }

  public void setResourcesIds(String resourcesIds) {
    this.resourcesIds = resourcesIds;
  }

  public AuthClientDetail scope(String scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  @ApiModelProperty(value = "")
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthClientDetail authClientDetail = (AuthClientDetail) o;
    return Objects.equals(this.id, authClientDetail.id) &&
        Objects.equals(this.accessTokenValidity, authClientDetail.accessTokenValidity) &&
        Objects.equals(this.additionalInformation, authClientDetail.additionalInformation) &&
        Objects.equals(this.authorities, authClientDetail.authorities) &&
        Objects.equals(this.autoapprove, authClientDetail.autoapprove) &&
        Objects.equals(this.clientId, authClientDetail.clientId) &&
        Objects.equals(this.clientSecret, authClientDetail.clientSecret) &&
        Objects.equals(this.grantTypes, authClientDetail.grantTypes) &&
        Objects.equals(this.partnerId, authClientDetail.partnerId) &&
        Objects.equals(this.redirectUri, authClientDetail.redirectUri) &&
        Objects.equals(this.refreshTokenValidity, authClientDetail.refreshTokenValidity) &&
        Objects.equals(this.resourcesIds, authClientDetail.resourcesIds) &&
        Objects.equals(this.scope, authClientDetail.scope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, accessTokenValidity, additionalInformation, authorities, autoapprove, clientId, clientSecret, grantTypes, partnerId, redirectUri, refreshTokenValidity, resourcesIds, scope);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthClientDetail {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    accessTokenValidity: ").append(toIndentedString(accessTokenValidity)).append("\n");
    sb.append("    additionalInformation: ").append(toIndentedString(additionalInformation)).append("\n");
    sb.append("    authorities: ").append(toIndentedString(authorities)).append("\n");
    sb.append("    autoapprove: ").append(toIndentedString(autoapprove)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    grantTypes: ").append(toIndentedString(grantTypes)).append("\n");
    sb.append("    partnerId: ").append(toIndentedString(partnerId)).append("\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("    refreshTokenValidity: ").append(toIndentedString(refreshTokenValidity)).append("\n");
    sb.append("    resourcesIds: ").append(toIndentedString(resourcesIds)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

