/*
 * Wallet
 * User application
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.wallet.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.wallet.sdk.model.AuthClientDetail;
import io.wallet.sdk.model.Link;
import io.wallet.sdk.model.Pagination;
import io.wallet.sdk.model.ValidationError;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * ClientDetailsListResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-24T22:57:23.435-05:00")
public class ClientDetailsListResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("clientDetailsList")
  private List<AuthClientDetail> clientDetailsList = null;

  @SerializedName("errors")
  private List<ValidationError> errors = null;

  @SerializedName("httpCode")
  private Integer httpCode = null;

  @SerializedName("httpMessage")
  private String httpMessage = null;

  @SerializedName("links")
  private List<Link> links = null;

  @SerializedName("page")
  private Pagination page = null;

  public ClientDetailsListResponse clientDetailsList(List<AuthClientDetail> clientDetailsList) {
    this.clientDetailsList = clientDetailsList;
    return this;
  }

  public ClientDetailsListResponse addClientDetailsListItem(AuthClientDetail clientDetailsListItem) {
    if (this.clientDetailsList == null) {
      this.clientDetailsList = new ArrayList<AuthClientDetail>();
    }
    this.clientDetailsList.add(clientDetailsListItem);
    return this;
  }

   /**
   * Get clientDetailsList
   * @return clientDetailsList
  **/
  @ApiModelProperty(value = "")
  public List<AuthClientDetail> getClientDetailsList() {
    return clientDetailsList;
  }

  public void setClientDetailsList(List<AuthClientDetail> clientDetailsList) {
    this.clientDetailsList = clientDetailsList;
  }

  public ClientDetailsListResponse errors(List<ValidationError> errors) {
    this.errors = errors;
    return this;
  }

  public ClientDetailsListResponse addErrorsItem(ValidationError errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<ValidationError>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @ApiModelProperty(value = "")
  public List<ValidationError> getErrors() {
    return errors;
  }

  public void setErrors(List<ValidationError> errors) {
    this.errors = errors;
  }

  public ClientDetailsListResponse httpCode(Integer httpCode) {
    this.httpCode = httpCode;
    return this;
  }

   /**
   * Get httpCode
   * @return httpCode
  **/
  @ApiModelProperty(value = "")
  public Integer getHttpCode() {
    return httpCode;
  }

  public void setHttpCode(Integer httpCode) {
    this.httpCode = httpCode;
  }

  public ClientDetailsListResponse httpMessage(String httpMessage) {
    this.httpMessage = httpMessage;
    return this;
  }

   /**
   * Get httpMessage
   * @return httpMessage
  **/
  @ApiModelProperty(value = "")
  public String getHttpMessage() {
    return httpMessage;
  }

  public void setHttpMessage(String httpMessage) {
    this.httpMessage = httpMessage;
  }

  public ClientDetailsListResponse links(List<Link> links) {
    this.links = links;
    return this;
  }

  public ClientDetailsListResponse addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<Link>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public ClientDetailsListResponse page(Pagination page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @ApiModelProperty(value = "")
  public Pagination getPage() {
    return page;
  }

  public void setPage(Pagination page) {
    this.page = page;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientDetailsListResponse clientDetailsListResponse = (ClientDetailsListResponse) o;
    return Objects.equals(this.clientDetailsList, clientDetailsListResponse.clientDetailsList) &&
        Objects.equals(this.errors, clientDetailsListResponse.errors) &&
        Objects.equals(this.httpCode, clientDetailsListResponse.httpCode) &&
        Objects.equals(this.httpMessage, clientDetailsListResponse.httpMessage) &&
        Objects.equals(this.links, clientDetailsListResponse.links) &&
        Objects.equals(this.page, clientDetailsListResponse.page);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientDetailsList, errors, httpCode, httpMessage, links, page);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientDetailsListResponse {\n");
    
    sb.append("    clientDetailsList: ").append(toIndentedString(clientDetailsList)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    httpCode: ").append(toIndentedString(httpCode)).append("\n");
    sb.append("    httpMessage: ").append(toIndentedString(httpMessage)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

