/*
 * Wallet
 * User application
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.wallet.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.wallet.sdk.model.Link;
import io.wallet.sdk.model.Pagination;
import io.wallet.sdk.model.ValidationError;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * UserBalanceResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-24T22:57:23.435-05:00")
public class UserBalanceResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("balanceAmount")
  private BigDecimal balanceAmount = null;

  @SerializedName("balanceCurrency")
  private String balanceCurrency = null;

  @SerializedName("errors")
  private List<ValidationError> errors = null;

  @SerializedName("httpCode")
  private Integer httpCode = null;

  @SerializedName("httpMessage")
  private String httpMessage = null;

  @SerializedName("links")
  private List<Link> links = null;

  @SerializedName("page")
  private Pagination page = null;

  @SerializedName("rewardAmount")
  private BigDecimal rewardAmount = null;

  @SerializedName("rewardCurrency")
  private String rewardCurrency = null;

  public UserBalanceResponse balanceAmount(BigDecimal balanceAmount) {
    this.balanceAmount = balanceAmount;
    return this;
  }

   /**
   * Get balanceAmount
   * @return balanceAmount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getBalanceAmount() {
    return balanceAmount;
  }

  public void setBalanceAmount(BigDecimal balanceAmount) {
    this.balanceAmount = balanceAmount;
  }

  public UserBalanceResponse balanceCurrency(String balanceCurrency) {
    this.balanceCurrency = balanceCurrency;
    return this;
  }

   /**
   * Get balanceCurrency
   * @return balanceCurrency
  **/
  @ApiModelProperty(value = "")
  public String getBalanceCurrency() {
    return balanceCurrency;
  }

  public void setBalanceCurrency(String balanceCurrency) {
    this.balanceCurrency = balanceCurrency;
  }

  public UserBalanceResponse errors(List<ValidationError> errors) {
    this.errors = errors;
    return this;
  }

  public UserBalanceResponse addErrorsItem(ValidationError errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<ValidationError>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @ApiModelProperty(value = "")
  public List<ValidationError> getErrors() {
    return errors;
  }

  public void setErrors(List<ValidationError> errors) {
    this.errors = errors;
  }

  public UserBalanceResponse httpCode(Integer httpCode) {
    this.httpCode = httpCode;
    return this;
  }

   /**
   * Get httpCode
   * @return httpCode
  **/
  @ApiModelProperty(value = "")
  public Integer getHttpCode() {
    return httpCode;
  }

  public void setHttpCode(Integer httpCode) {
    this.httpCode = httpCode;
  }

  public UserBalanceResponse httpMessage(String httpMessage) {
    this.httpMessage = httpMessage;
    return this;
  }

   /**
   * Get httpMessage
   * @return httpMessage
  **/
  @ApiModelProperty(value = "")
  public String getHttpMessage() {
    return httpMessage;
  }

  public void setHttpMessage(String httpMessage) {
    this.httpMessage = httpMessage;
  }

  public UserBalanceResponse links(List<Link> links) {
    this.links = links;
    return this;
  }

  public UserBalanceResponse addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<Link>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public UserBalanceResponse page(Pagination page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @ApiModelProperty(value = "")
  public Pagination getPage() {
    return page;
  }

  public void setPage(Pagination page) {
    this.page = page;
  }

  public UserBalanceResponse rewardAmount(BigDecimal rewardAmount) {
    this.rewardAmount = rewardAmount;
    return this;
  }

   /**
   * Get rewardAmount
   * @return rewardAmount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getRewardAmount() {
    return rewardAmount;
  }

  public void setRewardAmount(BigDecimal rewardAmount) {
    this.rewardAmount = rewardAmount;
  }

  public UserBalanceResponse rewardCurrency(String rewardCurrency) {
    this.rewardCurrency = rewardCurrency;
    return this;
  }

   /**
   * Get rewardCurrency
   * @return rewardCurrency
  **/
  @ApiModelProperty(value = "")
  public String getRewardCurrency() {
    return rewardCurrency;
  }

  public void setRewardCurrency(String rewardCurrency) {
    this.rewardCurrency = rewardCurrency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserBalanceResponse userBalanceResponse = (UserBalanceResponse) o;
    return Objects.equals(this.balanceAmount, userBalanceResponse.balanceAmount) &&
        Objects.equals(this.balanceCurrency, userBalanceResponse.balanceCurrency) &&
        Objects.equals(this.errors, userBalanceResponse.errors) &&
        Objects.equals(this.httpCode, userBalanceResponse.httpCode) &&
        Objects.equals(this.httpMessage, userBalanceResponse.httpMessage) &&
        Objects.equals(this.links, userBalanceResponse.links) &&
        Objects.equals(this.page, userBalanceResponse.page) &&
        Objects.equals(this.rewardAmount, userBalanceResponse.rewardAmount) &&
        Objects.equals(this.rewardCurrency, userBalanceResponse.rewardCurrency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(balanceAmount, balanceCurrency, errors, httpCode, httpMessage, links, page, rewardAmount, rewardCurrency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserBalanceResponse {\n");
    
    sb.append("    balanceAmount: ").append(toIndentedString(balanceAmount)).append("\n");
    sb.append("    balanceCurrency: ").append(toIndentedString(balanceCurrency)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    httpCode: ").append(toIndentedString(httpCode)).append("\n");
    sb.append("    httpMessage: ").append(toIndentedString(httpMessage)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    rewardAmount: ").append(toIndentedString(rewardAmount)).append("\n");
    sb.append("    rewardCurrency: ").append(toIndentedString(rewardCurrency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

