/*
 * Wallet
 * User application
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.wallet.sdk.api;

import io.wallet.sdk.api.ApiException;
import io.wallet.sdk.model.RestResponse;
import io.wallet.sdk.model.TelemetryRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for JsTrackerControllerApi
 */
//@Ignore
public class JsTrackerControllerApiTest {

    private final JsTrackerControllerApi api = new JsTrackerControllerApi( "", "");

    
    /**
     * trackMessage
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void trackMessageUsingPOSTTest() throws ApiException {
    
    	try{
    	
	        TelemetryRequest payload = null;
	        RestResponse response = api.trackMessageUsingPOST(payload);
	   }
	   catch(Exception e){
	   }

        // TODO: test validations
    }
    
}
