/*
 * Wallet
 * User application
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.wallet.sdk.api;

import io.wallet.sdk.api.ApiException;
import io.wallet.sdk.model.PartnerRequest;
import io.wallet.sdk.model.PartnerSignUpRequest;
import io.wallet.sdk.model.RestResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PartnerUiResourceApi
 */
//@Ignore
public class PartnerUiResourceApiTest {

    private final PartnerUiResourceApi api = new PartnerUiResourceApi( "", "");

    
    /**
     * createPartner
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createPartnerUsingPOSTTest() throws ApiException {
    
    	try{
    	
	        PartnerRequest partner = null;
	        RestResponse response = api.createPartnerUsingPOST(partner);
	   }
	   catch(Exception e){
	   }

        // TODO: test validations
    }
    
    /**
     * signUpPartner
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void signUpPartnerUsingPOSTTest() throws ApiException {
    
    	try{
    	
	        PartnerSignUpRequest partnerSignUp = null;
	        RestResponse response = api.signUpPartnerUsingPOST(partnerSignUp);
	   }
	   catch(Exception e){
	   }

        // TODO: test validations
    }
    
}
