/*
 * Wallet
 * User application
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.wallet.sdk.api;

import io.wallet.sdk.api.ApiException;
import io.wallet.sdk.model.ApplicationStatusResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StatusApiControllerApi
 */
//@Ignore
public class StatusApiControllerApiTest {

    private final StatusApiControllerApi api = new StatusApiControllerApi( "", "");

    
    /**
     * getAPIStatus
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAPIStatusUsingGETTest() throws ApiException {
    
    	try{
    	
	        ApplicationStatusResponse response = api.getAPIStatusUsingGET();
	   }
	   catch(Exception e){
	   }

        // TODO: test validations
    }
    
}
